apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
